[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/backend.dockerfile"

[deploy]
startCommand = "npx prisma generate && npx prisma migrate deploy && npx ts-node src/server.ts"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_ENV = "production"
PORT = "3002"
HOST = "0.0.0.0" 