version: "3.9"

services:
  backend:
    container_name: backend
    image: backend
    build:
      context: ../backend
      dockerfile: backend.dockerfile
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgresql://admin:1hEZ9ykWeANxPe1cm7XSMx0uW2Bvw8xS@dpg-cuahjl23esus73ems8s0-a.oregon-postgres.render.com/atipicidados_database
      - TZ=America/Sao_Paulo 
    volumes:
      - ./uploads:/backend/uploads
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      # Remova a dependência do `db` se ele não existir mais.
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ../frontend
      dockerfile: frontend.dockerfile 
    ports:
      - "3000:3000"  
    depends_on:
      - backend  
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

networks:
  app-network:
    driver: bridge
