[build]
builder = "DOCKERFILE"
dockerfilePath = "./backend.dockerfile"

[deploy]
startCommand = "npx ts-node src/server.ts"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
tbn-gijp-zmz
